import {
  Chain,
  arbitrum,
  avalanche,
  base,
  berachain,
  bitlayer,
  blast,
  bob,
  bounceBit,
  bsc,
  bsquared,
  coreDao,
  fantom,
  gnosis,
  linea,
  mainnet,
  manta,
  mantle,
  merlin,
  mode,
  optimism,
  polygon,
  polygonZkEvm,
  rootstock,
  scroll,
  sonic,
} from 'viem/chains';

export const CHAINS = new Map<string, Chain>([
  ['ethereum', mainnet],
  ['optimism', optimism],
  ['rootstock', rootstock],
  ['binance', bsc],
  ['gnosis', gnosis],
  ['polygon', polygon],
  ['sonic', sonic],
  ['manta', manta],
  ['bsquared', bsquared],
  ['fantom', fantom],
  ['zkevm', polygonZkEvm],
  ['core', coreDao],
  ['merlin', merlin],
  ['mantle', mantle],
  ['bouncebit', bounceBit],
  ['base', base],
  ['mode', mode],
  ['arbitrum', arbitrum],
  ['avalanche', avalanche],
  ['linea', linea],
  ['bob', bob],
  ['bera', berachain],
  ['blast', blast],
  ['bitlayer', bitlayer],
  ['scroll', scroll],
]);
